export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCESS = "OTP_VERIFY_SUCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";


export const CHECK_ELIGIBILITY_FOR_STASHFIN_REQUEST =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_REQUEST";
export const CHECK_ELIGIBILITY_FOR_STASHFIN_SUCESS =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_SUCESS";
export const CHECK_ELIGIBILITY_FOR_STASHFIN_FAILURE =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_FAILURE";

export const INIT_APPLICATION_FOR_STASHFIN_REQUEST =
  "INIT_APPLICATION_FOR_STASHFIN_REQUEST";
export const INIT_APPLICATION_FOR_STASHFIN_SUCESS =
  "INIT_APPLICATION_FOR_STASHFIN_SUCESS";
export const INIT_APPLICATION_FOR_STASHFIN_FAILURE =
  "INIT_APPLICATION_FOR_STASHFIN_FAILURE";

export const REGISTERATION_USER_FOR_STASHFIN_REQUEST =
  "REGISTERATION_USER_FOR_STASHFIN_REQUEST";
export const REGISTERATION_USER_FOR_STASHFIN_SUCESS =
  "REGISTERATION_USER_FOR_STASHFIN_SUCESS";
export const REGISTERATION_USER_FOR_STASHFIN_FAILURE =
  "REGISTERATION_USER_FOR_STASHFIN_FAILURE";
