export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCESS = "OTP_VERIFY_SUCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";

export const CHECK_STATUS_REQUEST = "CHECK_STATUS_REQUEST";
export const CHECK_STATUS_SUCCESS = "CHECK_STATUS_SUCCESS";
export const CHECK_STATUS_FAILURE = "CHECK_STATUS_FAILURE";

export const CHECK_ELIGIBILITY_FOR_STASHFIN_REQUEST =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_REQUEST";
export const CHECK_ELIGIBILITY_FOR_STASHFIN_SUCCESS =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_SUCCESS";
export const CHECK_ELIGIBILITY_FOR_STASHFIN_FAILURE =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_FAILURE";

export const SETTING_APPLICATION_ID_REQUEST = "SETTING_APPLICATION_ID_REQUEST";
export const SETTING_APPLICATION_ID_SUCCESS = "SETTING_APPLICATION_ID_SUCCESS";
export const SETTING_APPLICATION_ID_FAILURE = "SETTING_APPLICATION_ID_FAILURE";

export const GET_DASHBOARD_LOANS_DATA_REQUEST =
  "GET_DASHBOARD_LOANS_DATA_REQUEST";
export const GET_DASHBOARD_LOANS_DATA_SUCCESS =
  "GET_DASHBOARD_LOANS_DATA_SUCCESS";
export const GET_DASHBOARD_LOANS_DATA_FAILURE =
  "GET_DASHBOARD_LOANS_DATA_FAILURE";
