export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCESS = "OTP_VERIFY_SUCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";

export const CHECK_STATUS_REQUEST = "CHECK_STATUS_REQUEST";
export const CHECK_STATUS_SUCCESS = "CHECK_STATUS_SUCCESS";
export const CHECK_STATUS_FAILURE = "CHECK_STATUS_FAILURE";

export const CHECK_ELIGIBILITY_FOR_STASHFIN_REQUEST =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_REQUEST";
export const CHECK_ELIGIBILITY_FOR_STASHFIN_SUCCESS =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_SUCCESS";
export const CHECK_ELIGIBILITY_FOR_STASHFIN_FAILURE =
  "CHECK_ELIGIBILITY_FOR_STASHFIN_FAILURE";

export const INITIATE_APPLICATION_REQUEST = "INITIATE_APPLICATION_REQUEST";
export const INITIATE_APPLICATION_SUCCESS = "INITIATE_APPLICATION_SUCCESS";
export const INITIATE_APPLICATION_FAILURE = "INITIATE_APPLICATION_FAILURE";

export const GET_DASHBOARD_LOANS_DATA_REQUEST =
  "GET_DASHBOARD_LOANS_DATA_REQUEST";
export const GET_DASHBOARD_LOANS_DATA_SUCCESS =
  "GET_DASHBOARD_LOANS_DATA_SUCCESS";
export const GET_DASHBOARD_LOANS_DATA_FAILURE =
  "GET_DASHBOARD_LOANS_DATA_FAILURE";

export const TURN_ELIGIBLE_FLAG_REQUEST = "TURN_ELIGIBLE_FLAG_REQUEST";
export const TURN_ELIGIBLE_FLAG_SUCCESS = "TURN_ELIGIBLE_FLAG_SUCCESS";
export const TURN_ELIGIBLE_FLAG_FAILURE = "TURN_ELIGIBLE_FLAG_FAILURE";

export const PREFR_DEDUPE_SERVICE_REQUEST = "PREFR_DEDUPE_SERVICE_REQUEST";
export const PREFR_DEDUPE_SERVICE_SUCCESS = "PREFR_DEDUPE_SERVICE_SUCCESS";
export const PREFR_DEDUPE_SERVICE_FAILURE = "PREFR_DEDUPE_SERVICE_FAILURE";

export const REGISTER_START_PREFR_REQUEST = "REGISTER_START_PREFR_REQUEST";
export const REGISTER_START_PREFR_SUCCESS = "REGISTER_START_PREFR_SUCCESS";
export const REGISTER_START_PREFR_FAILURE = "REGISTER_START_PREFR_FAILURE";

export const GET_WEBVIEW_REQUEST = "GET_WEBVIEW_REQUEST";
export const GET_WEBVIEW_SUCCESS = "GET_WEBVIEW_SUCCESS";
export const GET_WEBVIEW_FAILURE = "GET_WEBVIEW_FAILURE";

export const SET_APPLICATION_ID_REQUEST = "SET_APPLICATION_ID_REQUEST";
export const SET_APPLICATION_ID_SUCCESS = "SET_APPLICATION_ID_SUCCESS";
export const SET_APPLICATION_ID_FAILURE = "SET_APPLICATION_ID_FAILURE";

export const SEND_APPLICATION_DETAILS_REQUEST = "SEND_APPLICATION_DETAILS_REQUEST";
export const SEND_APPLICATION_DETAILS_SUCCESS = "SEND_APPLICATION_DETAILS_SUCCESS";
export const SEND_APPLICATION_DETAILS_FAILURE = "SEND_APPLICATION_DETAILS_FAILURE";